---
title: "UF Covid Summary"
author: "Emilio M. Bruna"
date: "9/10/2020"
output: html_document
---

### The data used to generate these figures were extracted from [the UF Covid Dashboard](https://coronavirus.ufhealth.org/screen-test-protect-2/about-initiative/testing-dashboard/). All code and data can be found [here](https://github.com/embruna/UF_COVID).




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(gridExtra)
library(kableExtra)
# library(readr)
library(egg)
# library(magick)
# library(citr)
library(rvest)
library(RColorBrewer)
```



```{r LoadData, echo=FALSE,message = FALSE,cache=TRUE}

#save as a csv file with the date 
todays.data<-paste("./data_clean/UFcovid_data_",Sys.Date(),".csv",sep="")
uf.data<-read.csv(todays.data)
uf.data$update_date<-as.Date(uf.data$update_date)
```
\newline

```{r daily.pos.fig, message=FALSE, warning=FALSE, echo=FALSE}
source("./code/UF.plot.daily.R")
UF.plot.daily(uf.data)
```

\newline
```{r daily.n.fig,message=FALSE,warning=FALSE,echo=FALSE}
source("./code/UF.plot.daily.tests.R")
UF.plot.daily.tests(uf.data)
```


\newline
```{r cumulative.pos.fig, message=FALSE,warning=FALSE,echo=FALSE}
source("./code/UF.plot.cumul.pos.R")
UF.plot.cumul.pos(uf.data)
```


